stages:
  - build
  - deploy
build_image:
  stage: build
  variables:
    MESSAGE_TEXT: |
      Job: *BUILD*

      Service: [${CI_PROJECT_NAME}](${CI_PROJECT_URL})

      Branch: ${CI_COMMIT_BRANCH}
      ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} -> ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}

      Author: [${CI_COMMIT_AUTHOR}](${CI_SERVER_URL}/${CI_COMMIT_AUTHOR})
      Commit: [${CI_COMMIT_MESSAGE}](${CI_REPOSITORY_URL}/-/commit/${CI_COMMIT_SHA})

      Image: [`$CI_PROJECT_NAME:${CI_COMMIT_SHA:0:4}`](${CONTAINER_REGISTRY_URL}/${CI_PROJECT_NAME}/image)

  script:
    - cp $SETTINGS_XML settings.xml
    - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin cr.yandex
    - DOCKER_BUILDKIT=1 docker build -t cr.yandex/$REGISTRY_URL/$CI_PROJECT_NAME:${CI_COMMIT_SHA:0:4} .
    - docker push cr.yandex/$REGISTRY_URL/$CI_PROJECT_NAME:${CI_COMMIT_SHA:0:4}
    - docker tag cr.yandex/$REGISTRY_URL/$CI_PROJECT_NAME:${CI_COMMIT_SHA:0:4} cr.yandex/$REGISTRY_URL/$CI_PROJECT_NAME:latest
    - docker push cr.yandex/$REGISTRY_URL/$CI_PROJECT_NAME:latest
    - "curl -X POST -H \"Content-Type: application/json\" -d '{\"chat_id\": \"'\"$CHAT_ID\"'\", \"parse_mode\": \"markdown\", \"text\": \"'\"${MESSAGE_TEXT}\"'\"}' https://api.telegram.org/bot${BOT_TOKEN}/sendMessage"
  only:
    - main

deploy_to_prod:
  stage: deploy
  variables:
    MESSAGE_TEXT: |
      Job: *DEPLOY*

      Service: [${CI_PROJECT_NAME}](${CI_PROJECT_URL})

      Image: [`$CI_PROJECT_NAME:${CI_COMMIT_SHA:0:4}`](${CONTAINER_REGISTRY_URL}/${CI_PROJECT_NAME}/image)

  environment:
    name: staging
  script:
    - helm upgrade -f .k8s/values.yaml --set container.image=cr.yandex/$REGISTRY_URL/$CI_PROJECT_NAME:${CI_COMMIT_SHA:0:4} ${CI_PROJECT_NAME} djidjya-helm-chart/Djidjya-HelmChart
    - "curl -X POST -H \"Content-Type: application/json\" -d '{\"chat_id\": \"'\"$CHAT_ID\"'\", \"parse_mode\": \"markdown\", \"text\": \"'\"${MESSAGE_TEXT}\"'\"}' https://api.telegram.org/bot${BOT_TOKEN}/sendMessage"
  only:
    - main
